
enum {
	PP_ERROR = 0x1,
	SCANNER_ERROR = 0x100,
	PARSER_ERROR  = 0x200,
	SEMANT_ERROR  = 0x300,
	NO_ERROR = 0
};
/*
  P0000: no macro name given in #define directive
  P0001: no macro name given in #undef directive
  P0002: macro names must be identifier
  P0003: macro %s requres %d parameters
  P0004: function macro parenthesis is not close
  P0005: function macro parameter is not valid
  P0006: caller parameter is not valid

  P0010: #include is not followed by header-name
  P0011: %s no such file or directory

  P0020: #if directive is not found
  P0021: #endif directive is not found
  P0022: "defined" requires an identifier
  P0023: "defined" parenthesis is not close
  P0024: #ifdef is not followed by a identifier
  P0025: #ifndef is not followed by a identifier
  P0026: '#' is not followed by a macro parameter

  P0050: #error %s
  P0060: preprocessor syntax error
 */
enum PreprocessorError {
	PP_DEFINE_NO_MACRO_NAME = PP_ERROR,
	PP_UNDEF_NO_MACRO_NAME,
	PP_MACRO_NAME,
	PP_MACRO_PARAM_NOT_MATCH,
	PP_MACRO_PARENTHESIS_NOT_CLOSE,
	PP_MACRO_PARAM_NOT_VALID,
	PP_MACRO_CALLER_PARAM_NOT_VALID,

	PP_INCLUDE_NO_HEADER = PP_ERROR+10,
	PP_HEADER_IS_NOT_FOUND,

	PP_NO_IF = PP_ERROR+20,
	PP_NO_ENDIF,
	PP_DEFINED_OP_NO_IDENTIFIER,
	PP_DEFINED_PARENTHESIS_NOT_CLOSE,
	PP_IFDEF_NO_IDENTIFIER,
	PP_IFNDEF_NO_IDENTIFIER,
	PP_TO_STR_OP_NO_PARAM,

	PP_ERROR_DIRECTIVE = PP_ERROR+50,
	PP_SYNTAX_ERROR = PP_ERROR+60,
};

/*
  S0001: floating value is not supported
  S0002: new-line in string literal
  S0003: unknown token %s
 */
enum ScannerError {
	SC_FLOAT_LITERAL = SCANNER_ERROR,
	SC_NEW_LINE_IN_STRING,
	SC_UNKNOWN_TOKEN,
};
/*
  Y0001: 
 */
enum ParserError {
	PA_PRIMARY_EXP_PARENTHESIS_NOT_CLOSE	 = PARSER_ERROR,
	PA_SCOPE_IDENTIFIER,
	PA_CXXCAST_NOT_VALID,
	PA_POSTFIX_EXP_BRACKET_NOT_CLOSE,
	PA_POSTFIX_EXP_PARENTHESIS_NOT_CLOSE,
	PA_DOT_OP_NOT_VALID,
	PA_ARROW_OP_NOT_VALID,
	PA_POSTFIX_EXP_NOT_VALID,
	PA_EXP_EXPECTED,
	PA_UNARY_EXP_NOT_VALID,
	PA_BINARY_EXP_NOT_VALID,
	PA_CONDITIONAL_EXP_NOT_VALID,
	PA_ASSIGNMENT_EXP_NOT_VALID,
	PA_LABEL_STATEMENT_NOT_VALID,
	PA_CASE_STATEMENT_NOT_VALID,
	PA_DEFAULT_STATEMENT_NOT_VALID,
	PA_COMPOUND_STATEMENT_NOT_CLOSE,
	PA_IF_STATEMENT_NOT_VALID,
	PA_SWITCH_STATEMENT_NOT_VALID,
	PA_ELSE_STATEMENT_NOT_VALID,
	PA_CONDITION_NOT_VALID,
	PA_WHILE_STATEMENT_NOT_VALID,
	PA_DO_STATEMENT_NOT_VALID,
	PA_FOR_STATEMENT_NOT_VALID,
	PA_JUMP_STATEMENT_NOT_VALID,
	PA_CONTINUE_STATEMENT_NOT_VALID,
	PA_RETURN_STATEMENT_NOT_VALID,
	PA_GOTO_STATEMENT_NOT_VALID,
	PA_DECLARATION_SEMICOLON,
	PA_DECLARATION_LBRACE_FOLLOW,
	PA_DECLARATION_NOT_VALID,
	PA_TYPEDEF_NAME_NOT_VALID,
	PA_INIT_DECLARATOR_LIST_NOT_FOLLOW_SEMICOLON,
	PA_DECL_SPEC_BASE_TYPE_NOT_SPECIFIED,
	PA_TYPENAME_TEMPLATE_ID_EXPECTED,
	PA_ELABORATED_TYPE_IDENT_EXPECTED,
	PA_ELABORATED_TYPE_TEMPLATEID_EXPECTED,
	PA_ELABORATED_TYPE_NESTED_NAME_EXPECTED,
	PA_ENUMERATOR_EXPECTED,
	PA_ENUMERATOR_ASSIGN_EXP_EXPECTED,
	PA_NAMESPACE_NOT_VALID,
	PA_USING_NOT_VALID,
	PA_INIT_DECLARATOR_EXPECTED,
	PA_ABSTRACT_DECLARATOR_EXPECTED,
	PA_PARAMETER_DECLARATION_EXPECTED,
	PA_PARAMETER_DECLARATION_ASSIGN_EXP_EXPECTED,
	PA_INITIALIZER_ASSIGN_NOT_VALID,
	PA_INITIALIZER_PARENTHESIS_NOT_VALID,
	PA_INITIALIZER_CLAUSE_BRACE_NOT_VALID,
	PA_INITIALIZER_CLAUSE_EXPECTED,
	PA_CLASS_IDENT_EXPECTED,
	PA_ACCESS_SPECIFIER_COLON_EXPECTED,
	PA_MEMBER_DECL_UNQUALIFIED_ID_EXPECTED,
	PA_CONSTANT_INITIALIZER_EXP_EXPECTED,
	PA_BASE_CLAUSE_BASE_SPECIFIER_EXPECTED,
	PA_BASE_SPECIFIER_CLASSNAME_EXPECTED,
	PA_CTOR_INITIALIZER_LIST_EXPECTED,
	PA_MEM_INITIALIZER_EXPECTED,
	PA_MEM_INITIALIZER_PARENTHESIS_EXPECTED,
	PA_OPERATOR_ID_RPAREN_EXPECTED,
	PA_OPERATOR_ID_RBRACKET_EXPECTED,
	PA_TEMPLATE_PARAMETER_EXPECTED,
	PA_TYPE_PARAMETER_TYPE_ID_EXPECTED,
	PA_TYPE_PARAMETER_ID_EXP_EXPECTED,
	PA_TYPE_PARAMETER_TEMPLATE_NOT_VALID,
};

enum SemanticError {
	SE_ERROR = SEMANT_ERROR,
	SE_UNDEFINED_SYMBOL,
	SE_CAN_NOT_CONVERT,
	SE_ASSIGN_READONLY,
	SE_TWO_OR_MORE_BASETYPE,
	SE_SIGN_SPECIFIER,
	SE_VOID_DECL,
	SE_INVALID_CONST,
	SE_ARRAY_SIZE_NOT_CONST,
	SE_ARRAY_INDEX_NOT_VALID,
	SE_ARRAY_INDEX_RANGE_NOT_VALID,
	SE_COND_EXP_DIFF_TYPE,
	SE_EXPECTED_CONST_EXP,
	SE_NUMBER_OF_FUNC_PARAMS_NOT_VALID,
	SE_FUNC_PARAM_TYPE_NOT_VALID,
	SE_DUPLICATE_FUNC_DEF,
	SE_DUPLICATE_SYMBOL,
	SE_DUPLICATE_TYPE,
	SE_RETURN_VALUE_IN_VOID_FUNC,
	SE_ENUM_ASSIGN,
	SE_CANT_ACCESS_TO_MEMBER,
	SE_SWITCH_COND_MUSTBE_INT,
	SE_SWITCH_DEFAULT,
	SE_UNARY_SIGN,
	SE_UNARY_STAR,
	SE_UNARY_OP_NOT_ALLOWED,
	SE_UNDEFINED_LABEL,
	SE_DUPLICATE_LABEL,
};
